title: Professor Ejaz # your name (or website title) here
logo: "/images/WhatsApp Image 2021-08-19 at 1.08.11 PM.jpeg?raw=true" # your photo (or logo) here
description: > I have started my career in Saqara School and Academy in Pakistan as Urdu Lecturer. I worked here for four years. Then I joined Superior Group of Colleges in the period of  2013-18.
I worked here as a  Head of Department (URDU) and Assistant Examination Controller. I got the best teacher award of the year 2016. I got appreciation award in the year of 2014.I also worked here as a HR,Transport Incharge and as Discipline Incharge.
Then i joined Punjab Group of Colleges in the period of 2018-20. Here, i worked as a Head of Department (Urdu).Here,I got the best Teacher award of the year 2019. 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
