title: Professor Ejaz # your name (or website title) here
logo: "/images/WhatsApp Image 2021-08-19 at 1.08.11 PM.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Contact Information 
  <br><br>
   <b>Email   :      </b> linq2ejaz@gmail.com <br>
   <b>Phone Number : </b>   +92 308 6070920 <br> 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal

